### ISSUE TITLE
Multiple monitor support

### ISSUE THREAD

**Issue by MohnJadden** [evangreen/starryn#1]
Would it be possible to get multi-monitor support?  It'd be great to have this run on my dual monitor setup, or people with multi-monitors could REALLY get big cityscapes. 

Either way, thank you for making this - it's a mainstay on any computer I'm on, takes me back to when I had the real deal as a kid!

**Comment by evangreen** [comment]
Thanks for the kudos, it's much appreciated!

That should be doable. I need to figure out what to replace [this](https://github.com/evangreen/starryn/blob/master/starryn.c#L462) with to support multiple monitors. If you know of any literature or examples, point me towards them. Otherwise I'll do some Googling when I find some free time.

**Comment by evangreen** [comment]
Probably something [here](https://stackoverflow.com/questions/1834771/how-do-you-get-createwindowex-to-create-the-window-on-a-specific-monitor) would help me

**Comment by evangreen** [comment]
I pushed some changes, want to give it a try?

**Comment by evangreen** [comment]
Closing as Fixed, let me know if you run into issues.
